[workspace]
members = ["crates/*"]

[package]
name = "toph"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
hostname = "0.3.1"
logfmt = { path = "crates/logfmt" }

[profile.release]
strip = true
