[package]
name = "logfmt"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.17.1"
parking_lot = "0.12.1"
thiserror = "1.0.40"
time = { version = "0.3.20", features = ["std", "formatting", "local-offset"] }
